# Generated by Django 4.2.7 on 2023-12-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_firstname_remove_member_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='account',
            new_name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='password2',
            field=models.CharField(default='', max_length=256),
        ),
    ]
